"""Context compaction — summarize older messages to free token budget.

Strategy:
  1. Keep the system message (index 0) intact
  2. Keep the most recent N turns intact (configurable)
  3. Summarize everything in between into a single "prior conversation summary"
  4. Replace the middle section with the summary message

The summary is generated by calling the LLM with a compaction prompt.
If the LLM is unavailable, a simple truncation fallback is used.
"""

from __future__ import annotations

from coding_agent.core.logging import get_logger
from coding_agent.core.types import Message, Role

log = get_logger("agent.compaction")

COMPACTION_PROMPT = """Summarize the following conversation history concisely. Focus on:
- What the user asked for
- What actions were taken (files read/written/edited, commands run)
- Key findings and decisions
- Current state of the task

Be factual and specific. Include file paths and function names when relevant.
Keep the summary under 500 words.

Conversation to summarize:
"""


def _format_messages_for_summary(messages: list[Message]) -> str:
    parts: list[str] = []
    for msg in messages:
        if msg.role == Role.USER:
            parts.append(f"User: {msg.content}")
        elif msg.role == Role.ASSISTANT:
            text = msg.content or ""
            if msg.tool_calls:
                calls = ", ".join(f"{tc.name}({tc.arguments})" for tc in msg.tool_calls)
                text += f"\n[Tool calls: {calls}]"
            parts.append(f"Assistant: {text}")
        elif msg.role == Role.TOOL:
            for tr in msg.tool_results:
                status = "OK" if tr.ok else "FAIL"
                content = tr.content
                if len(content) > 200:
                    content = content[:200] + "..."
                parts.append(f"Tool({tr.tool}) [{status}]: {content}")
    return "\n\n".join(parts)


def split_for_compaction(
    messages: list[Message],
    keep_recent: int = 6,
) -> tuple[list[Message], list[Message], list[Message]]:
    """Split messages into (system, compactable_middle, recent_tail).

    Returns three lists:
      - system: the system message (always index 0 if present)
      - middle: messages to be summarized
      - tail: recent messages to keep verbatim
    """
    if not messages:
        return [], [], []

    system: list[Message] = []
    rest = list(messages)

    if rest and rest[0].role == Role.SYSTEM:
        system = [rest[0]]
        rest = rest[1:]

    if len(rest) <= keep_recent:
        return system, [], rest

    cut = len(rest) - keep_recent
    middle = rest[:cut]
    tail = rest[cut:]

    return system, middle, tail


def build_summary_message(summary_text: str) -> Message:
    return Message(
        role=Role.USER,
        content=f"[Prior conversation summary]\n\n{summary_text}\n\n[End of summary — conversation continues below]",
    )


async def compact_messages(
    messages: list[Message],
    provider,
    *,
    keep_recent: int = 6,
) -> list[Message]:
    """Compact the message list by summarizing older turns.

    Uses the LLM to generate a summary. Falls back to simple truncation
    if the LLM call fails.
    """
    system, middle, tail = split_for_compaction(messages, keep_recent=keep_recent)

    if not middle:
        log.info("compaction_skipped", reason="nothing to compact")
        return messages

    log.info(
        "compaction_start",
        middle_count=len(middle),
        tail_count=len(tail),
    )

    formatted = _format_messages_for_summary(middle)
    summary_text = await _llm_summarize(formatted, provider)

    if not summary_text:
        summary_text = _fallback_summarize(middle)

    summary_msg = build_summary_message(summary_text)
    compacted = [*system, summary_msg, *tail]

    log.info(
        "compaction_done",
        original_count=len(messages),
        compacted_count=len(compacted),
    )

    return compacted


async def _llm_summarize(text: str, provider) -> str | None:
    """Call the LLM to summarize conversation history."""
    from coding_agent.core.types import StreamEventType

    prompt_msg = Message(role=Role.USER, content=COMPACTION_PROMPT + text)

    try:
        parts: list[str] = []
        async for event in provider.stream([prompt_msg], [], temperature=0.0):
            if event.type == StreamEventType.TEXT_DELTA and event.text:
                parts.append(event.text)
            elif event.type == StreamEventType.ERROR:
                log.warning("compaction_llm_error", error=event.error)
                return None
        return "".join(parts) if parts else None
    except Exception as e:
        log.warning("compaction_llm_failed", error=str(e))
        return None


def _fallback_summarize(messages: list[Message]) -> str:
    """Simple truncation fallback when LLM is unavailable."""
    parts: list[str] = []
    for msg in messages:
        if msg.role == Role.USER:
            parts.append(f"- User asked: {msg.content[:100]}")
        elif msg.role == Role.ASSISTANT and msg.tool_calls:
            calls = ", ".join(tc.name for tc in msg.tool_calls)
            parts.append(f"- Assistant called tools: {calls}")
        elif msg.role == Role.ASSISTANT and msg.content:
            parts.append(f"- Assistant replied: {msg.content[:100]}")
    return "Conversation summary (truncated):\n" + "\n".join(parts)
